spring.application.name=MedicineTracker
server.servlet.context-path=/MedTrack

spring.datasource.url=jdbc:h2:file:./data/medicinetrackerdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Ignore thymeleaf cache for development
spring.thymeleaf.cache=false

# File upload limit if any
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Default port
server.port=8080
